version: "3.8"
services:
  db:
    image: "mysql:8.0.21"
    container_name: "backend-database"
    volumes:
      - backend-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tPMAGwSH4h2C
    ports:
      - "3306:3306"

  backend-api:
    image: "zeklouis/phalcon-devtools:latest"
    container_name: "backend-api"
    volumes:
      - ./api:/var/www/
    ports:
      - "80:80"
      - "443:443"
    links:
      - "db:mysql"
    depends_on:
      - db

  backend-pma:
    image: "phpmyadmin/phpmyadmin"
    container_name: "backend-pma"
    links:
      - "db:mysql"
    ports:
      - "10001:80"
    depends_on:
      - db

volumes:
  backend-database: